name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version: [0.12.0, 0.13.0, master]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}
      - name: Build
        run: zig build -Dxslt
